### ISSUE TITLE
First `$STARSHIP_PROMPT` example doesn't to work / path not taken as absolut

### ISSUE THREAD

**Issue by yggdr** [anki-code/xontrib-prompt-starship#13]
Using the first example of creating a short toml, setting `$STARSHIP_CONFIG` to a string like `~/.config/stuff.toml` or `$HOME/.config/other_stuff.toml` does not pick up those configuration files. After experimenting with `starship config` a bit it seems that the value of `$STARSHIP_CONFIG` isn't actually taken to be an absolut path (with `~` or `$HOME` properly expanded), but instead an unexpanded path relative to the current directory. So `starship config` would try to open the non-existing file `/current/working/directory/~/.config/stuff.toml`.

**Comment by anki-code** [comment]
PR with fix is welcome!

**Comment by yggdr** [comment]
After looking into how xontribs work and investigating the underlying issue, I can give you two possible solutions:
The short fix https://github.com/anki-code/xontrib-prompt-starship/pull/14 which only introduces a `Path(...).expanduser()` at one point, and the slightly longer fix https://github.com/anki-code/xontrib-prompt-starship/pull/15 which does some minor refactoring, moving the expanduser responsibility completely outside the `_starship_prompt` function.

I would prefer the longer version.

**Comment by anki-code** [comment]
Hey @yggdr! Thank you for two options. I asked question in #15 .

**Comment by yggdr** [comment]
I don't see a question in either PR.

**Comment by anki-code** [comment]
<img width="922" alt="image" src="https://github.com/anki-code/xontrib-prompt-starship/assets/1708680/0aeb7795-c95e-49d9-ab72-152f2842c995">

**Comment by yggdr** [comment]
Strange, I still do not see anything in the PR itself?! But to answer your question: that was a mistake when rearranging some code, apparently I didn't test thoroughly again afterwards. I corrected it to `STARSHIP_CONFIG`. That way, left-cfg falls back to it if no side-specific prompt is set.
