### ISSUE TITLE
$STARSHIP_SESSION_KEY

### ISSUE THREAD

**Issue by bestlem** [anki-code/xontrib-prompt-starship#2]
I am not running this xontrib but I have starship running in xonsh

I needed to also set STARSHIP_SESSION_KEY

This is to give different logs for each terminal

In me .xonshrc I have
```
$STARSHIP_SESSION_KEY = $(starship session)
```

**Comment by anki-code** [comment]
Hi @bestlem ! Added in 0.0.5. Please update: `pip install -U xontrib-prompt-starship`.
