### ISSUE TITLE
The default prompt arrow does not reflect the vi mode

### ISSUE THREAD

**Issue by taranlu-houzz** [anki-code/xontrib-prompt-starship#6]
In other shells (at least, in `fish`), when you activate `vi` mode, the `starship` prompt arrow reverses direction to indicate the difference between "insert" mode vs "command" mode. This does not appear to be working with the `starship`/`xonsh` integration.

**Comment by anki-code** [comment]
Does this actual to [the xonsh support in the starship](https://github.com/starship/starship#step-2-setup-your-shell-to-use-starship)?

**Comment by taranlu-houzz** [comment]
@anki-code Haha, yeah, actually, the same thing happens with the setup they recommend. I thought this problem seemed familiar; I actually submitted a issue about it a while back but forgot about that: https://github.com/starship/starship/issues/3614

**Comment by taranlu-houzz** [comment]
I guess this is not really an issue with this xontrib then, so I will close the issue.
