### ISSUE TITLE
multi-line prompt not taking up full terminal

### ISSUE THREAD

**Issue by cycomanic** [anki-code/xontrib-prompt-starship#8]
I'm using a multi-line prompt in starship which works correctly in fish, however  only takes up a fraction of the terminal size in xonsh.

Starship example setup
```
format = """
AA$fill\
$time\
$line_break\
$character
"""

[fill]
symbol = "."

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"
```

in fish this looks like this:

+-----------------------------------------------------------------------------------------------------------------------------------------------+
|AA........................................................................................................................................................11:45:31|
|❯                                                                                                                                                                             

if I use the same in xonsh with xontrib-prompt-starship: 

+-----------------------------------------------------------------------------------------------------------------------------------------------+
|AA......................................................................11:45:36                                                                                     |
|❯                                                                                                                                                                              

Note the prompt only fills up half the terminal window. I get similar behavior if I create a right prompt, which is also not aligned to the right of the terminal. If I use [xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) I get the same issue, however if I specify `#noesc` it fixes the issue (however I loose the color in my prompt).

**Comment by anki-code** [comment]
PR is welcome!

**Comment by cycomanic** [comment]
Fixed it, but forgot to create the pull request. Done now.
